import { createFileRoute, Link } from '@tanstack/react-router';
import { useSuspenseQuery } from '@tanstack/react-query';
import { blogQuery } from '@/lib/blog-queries';
import { pageHead } from '@/lib/seo';
export const Route = createFileRoute('/blog/')({ head: () => pageHead('The Journal | StoryGuide Blog', 'Reading notes, reflections and perspectives from the StoryGuide desk.', '/blog'), loader: ({ context }) => context.queryClient.ensureQueryData(blogQuery), component: Blog, errorComponent: () => <div className="editorial-container content-page"><h1>The journal is resting.</h1><p>Please try again shortly.</p></div>, notFoundComponent: () => <p>Journal not found.</p> });
function Blog() {
  const { data: posts } = useSuspenseQuery(blogQuery);
  return <div className="editorial-container content-page journal-page"><div className="page-intro"><p className="eyebrow">From the StoryGuide desk</p><h1>The Journal</h1><p>On reading, being human, and seeing things a little differently.</p></div><div className="journal-heading"><span className="small-label">Notes & perspectives</span><span className="small-label">{posts.length} {posts.length === 1 ? 'article' : 'articles'}</span></div>{posts.length ? posts.map((post, i) => <article className="journal-entry" key={post.id}><span className="journal-number">{String(i + 1).padStart(2, '0')}</span><div><time className="small-label">{new Date(post.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' })}</time><Link to="/blog/$slug" params={{ slug: post.slug }}><h2>{post.title}</h2></Link><p>{post.excerpt}</p><Link to="/blog/$slug" params={{ slug: post.slug }} className="text-link">Read the article →</Link></div></article>) : <div className="journal-empty"><h2>A fresh page.</h2><p>Our first notes are still taking shape. Until then, there’s a whole shelf to explore.</p><Link to="/ebooks" search={{}} className="text-link">Find your next read →</Link></div>}<div className="journal-owner"><Link to="/admin" className="text-link">Admin desk →</Link></div></div>;
}
