/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BlogEditorRouteImport } from './routes/blog-editor'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EbooksRouteImport } from './routes/ebooks'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as EbooksIndexRouteImport } from './routes/ebooks.index'
import { Route as EbooksSlugRouteImport } from './routes/ebooks.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEditorRoute = BlogEditorRouteImport.update({
  id: '/blog-editor',
  path: '/blog-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksRoute = EbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const EbooksIndexRoute = EbooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EbooksRoute,
} as any)
const EbooksSlugRoute = EbooksSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EbooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog-editor': typeof BlogEditorRoute
  '/contact': typeof ContactRoute
  '/ebooks': typeof EbooksRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog-editor': typeof BlogEditorRoute
  '/contact': typeof ContactRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/blog': typeof BlogIndexRoute
  '/ebooks': typeof EbooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/blog-editor': typeof BlogEditorRoute
  '/contact': typeof ContactRoute
  '/ebooks': typeof EbooksRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/blog-editor'
    | '/contact'
    | '/ebooks'
    | '/blog/$slug'
    | '/ebooks/$slug'
    | '/blog/'
    | '/ebooks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/blog-editor'
    | '/contact'
    | '/blog/$slug'
    | '/ebooks/$slug'
    | '/blog'
    | '/ebooks'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/blog-editor'
    | '/contact'
    | '/ebooks'
    | '/blog/$slug'
    | '/ebooks/$slug'
    | '/blog/'
    | '/ebooks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  BlogEditorRoute: typeof BlogEditorRoute
  ContactRoute: typeof ContactRoute
  EbooksRoute: typeof EbooksRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog-editor': {
      id: '/blog-editor'
      path: '/blog-editor'
      fullPath: '/blog-editor'
      preLoaderRoute: typeof BlogEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks': {
      id: '/ebooks'
      path: '/ebooks'
      fullPath: '/ebooks'
      preLoaderRoute: typeof EbooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/ebooks/': {
      id: '/ebooks/'
      path: '/'
      fullPath: '/ebooks/'
      preLoaderRoute: typeof EbooksIndexRouteImport
      parentRoute: typeof EbooksRoute
    }
    '/ebooks/$slug': {
      id: '/ebooks/$slug'
      path: '/$slug'
      fullPath: '/ebooks/$slug'
      preLoaderRoute: typeof EbooksSlugRouteImport
      parentRoute: typeof EbooksRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EbooksRouteChildren {
  EbooksSlugRoute: typeof EbooksSlugRoute
  EbooksIndexRoute: typeof EbooksIndexRoute
}

const EbooksRouteChildren: EbooksRouteChildren = {
  EbooksSlugRoute: EbooksSlugRoute,
  EbooksIndexRoute: EbooksIndexRoute,
}

const EbooksRouteWithChildren =
  EbooksRoute._addFileChildren(EbooksRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  BlogEditorRoute: BlogEditorRoute,
  ContactRoute: ContactRoute,
  EbooksRoute: EbooksRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
